// <auto-generated />
namespace Kapitalist.Data.Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DraftTenderContactPoints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DraftTenderContactPoints));
        
        string IMigrationMetadata.Id
        {
            get { return "201610140622344_DraftTenderContactPoints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
