//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapitalist.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kapitalist.Web.Resources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про компанію.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відкриті торги з публікацією англ. мовою.
        /// </summary>
        public static string AboveThresholdEN {
            get {
                return ResourceManager.GetString("AboveThresholdEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відкриті торги.
        /// </summary>
        public static string AboveThresholdUA {
            get {
                return ResourceManager.GetString("AboveThresholdUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відсутній.
        /// </summary>
        public static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати відповідь.
        /// </summary>
        public static string AddAnswer {
            get {
                return ResourceManager.GetString("AddAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати вимогу/скаргу.
        /// </summary>
        public static string AddClaimComplaint {
            get {
                return ResourceManager.GetString("AddClaimComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати контакт.
        /// </summary>
        public static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати документ.
        /// </summary>
        public static string AddDocument {
            get {
                return ResourceManager.GetString("AddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати критерій.
        /// </summary>
        public static string AddFeature {
            get {
                return ResourceManager.GetString("AddFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати значення особливої вимоги.
        /// </summary>
        public static string AddFeatureValue {
            get {
                return ResourceManager.GetString("AddFeatureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати закупку.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додаткова класифікація.
        /// </summary>
        public static string AdditionalClassification {
            get {
                return ResourceManager.GetString("AdditionalClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати лот.
        /// </summary>
        public static string AddLot {
            get {
                return ResourceManager.GetString("AddLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати запитання.
        /// </summary>
        public static string AddQuestion {
            get {
                return ResourceManager.GetString("AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відповідь.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата приймання пропозицій.
        /// </summary>
        public static string ApplicationsSubmissionDate {
            get {
                return ResourceManager.GetString("ApplicationsSubmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аукціон.
        /// </summary>
        public static string Auction {
            get {
                return ResourceManager.GetString("Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата аукціону.
        /// </summary>
        public static string AuctionDate {
            get {
                return ResourceManager.GetString("AuctionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Визначення.
        /// </summary>
        public static string Award {
            get {
                return ResourceManager.GetString("Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Критерій вибору переможця.
        /// </summary>
        public static string AwardCriteria {
            get {
                return ResourceManager.GetString("AwardCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Backward {
            get {
                return ResourceManager.GetString("Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допорогові закупівлі.
        /// </summary>
        public static string BelowThreshold {
            get {
                return ResourceManager.GetString("BelowThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приєднати до лоту.
        /// </summary>
        public static string BindLot {
            get {
                return ResourceManager.GetString("BindLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відміна.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відміна тендеру.
        /// </summary>
        public static string CancelTender {
            get {
                return ResourceManager.GetString("CancelTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис причини відміни закупівлі.
        /// </summary>
        public static string CancelTenderDescription {
            get {
                return ResourceManager.GetString("CancelTenderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл с описом причини відміни тендеру.
        /// </summary>
        public static string CancelTenderFileDescription {
            get {
                return ResourceManager.GetString("CancelTenderFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довідка.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити профіль.
        /// </summary>
        public static string ChangeProfile {
            get {
                return ResourceManager.GetString("ChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; обов&apos;язкове..
        /// </summary>
        public static string CheckIfAttribute {
            get {
                return ResourceManager.GetString("CheckIfAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вимога.
        /// </summary>
        public static string Claim {
            get {
                return ResourceManager.GetString("Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата періоду уточнень.
        /// </summary>
        public static string ClarificationDate {
            get {
                return ResourceManager.GetString("ClarificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класифікація.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to натисніть наступну кнопку.
        /// </summary>
        public static string ClickNextButton {
            get {
                return ResourceManager.GetString("ClickNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наіменування компанії.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип компанії.
        /// </summary>
        public static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юридична особа.
        /// </summary>
        public static string CompanyType_Corporation {
            get {
                return ResourceManager.GetString("CompanyType_Corporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фізична особа.
        /// </summary>
        public static string CompanyType_Individual {
            get {
                return ResourceManager.GetString("CompanyType_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{1}&quot; і &quot;{0}&quot; не співпадають..
        /// </summary>
        public static string CompareAttribute {
            get {
                return ResourceManager.GetString("CompareAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скарга.
        /// </summary>
        public static string Complaint {
            get {
                return ResourceManager.GetString("Complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скарги.
        /// </summary>
        public static string Complaints {
            get {
                return ResourceManager.GetString("Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердити.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердження .
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалось відправити електронний лист з підтвердженням реєстрації..
        /// </summary>
        public static string ConfirmationEmailSendError {
            get {
                return ResourceManager.GetString("ConfirmationEmailSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронний лист з підтвердженням реєстрації відправлений на скриньку {0}.
        /// </summary>
        public static string ConfirmationEmailSent {
            get {
                return ResourceManager.GetString("ConfirmationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевірте свою поштову скриньку, та слідуйте інструкціям в листі. Якщо ви не можете знайти лист з підтвердженням - можливо він попав в папку &quot;спам&quot;..
        /// </summary>
        public static string ConfirmationEmailSentDescr {
            get {
                return ResourceManager.GetString("ConfirmationEmailSentDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердіть E-mail.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердити новий пароль.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердіть пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вітаємо!.
        /// </summary>
        public static string Congratulation {
            get {
                return ResourceManager.GetString("Congratulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакт.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Країна.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класифікатор ДК 021:2015 (CPV).
        /// </summary>
        public static string CpvCode {
            get {
                return ResourceManager.GetString("CpvCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити тендер-чернетку.
        /// </summary>
        public static string CreateDraftTender {
            get {
                return ResourceManager.GetString("CreateDraftTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити новий аккаунт.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валюта.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточний пароль.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замовнику.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити закупівлю.
        /// </summary>
        public static string CustomerUnderLine {
            get {
                return ResourceManager.GetString("CustomerUnderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місце доставки.
        /// </summary>
        public static string DeliveryLocation {
            get {
                return ResourceManager.GetString("DeliveryLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис англ..
        /// </summary>
        public static string DescriptionEn {
            get {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документи.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип документу.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тендер-чернетка.
        /// </summary>
        public static string DraftTender {
            get {
                return ResourceManager.GetString("DraftTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати вимогу/скаргу.
        /// </summary>
        public static string EditClaimComplaint {
            get {
                return ResourceManager.GetString("EditClaimComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування документу.
        /// </summary>
        public static string EditDocument {
            get {
                return ResourceManager.GetString("EditDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати тендер-чернетку.
        /// </summary>
        public static string EditDraftTender {
            get {
                return ResourceManager.GetString("EditDraftTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати особливу вимогу.
        /// </summary>
        public static string EditFeature {
            get {
                return ResourceManager.GetString("EditFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати значення особливої вимоги.
        /// </summary>
        public static string EditFeatureValue {
            get {
                return ResourceManager.GetString("EditFeatureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати об&apos;єкт закупівлі.
        /// </summary>
        public static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати лот.
        /// </summary>
        public static string EditLot {
            get {
                return ResourceManager.GetString("EditLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування персональних данних.
        /// </summary>
        public static string EditPersonalData {
            get {
                return ResourceManager.GetString("EditPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати тендер.
        /// </summary>
        public static string EditTender {
            get {
                return ResourceManager.GetString("EditTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Висота.
        /// </summary>
        public static string Elevation {
            get {
                return ResourceManager.GetString("Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Е-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; містить невірну e-mail адресу..
        /// </summary>
        public static string EmailAddressAttribute {
            get {
                return ResourceManager.GetString("EmailAddressAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердження електронної пошти.
        /// </summary>
        public static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закінчення періоду.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прийняття питань.
        /// </summary>
        public static string Enquery {
            get {
                return ResourceManager.GetString("Enquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виникла помилка. Будь ласка спробуйте ще раз.
        /// </summary>
        public static string error_occured {
            get {
                return ResourceManager.GetString("error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підчас обробки вашого запиту виникла помилка..
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факс.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нецінові (якісні) критерії оцінки.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис опції.
        /// </summary>
        public static string FeatureValueDescription {
            get {
                return ResourceManager.GetString("FeatureValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис опції англ..
        /// </summary>
        public static string FeatureValueDescriptionEn {
            get {
                return ResourceManager.GetString("FeatureValueDescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва опції.
        /// </summary>
        public static string FeatureValueName {
            get {
                return ResourceManager.GetString("FeatureValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва опції англ..
        /// </summary>
        public static string FeatureValueNameEn {
            get {
                return ResourceManager.GetString("FeatureValueNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опції.
        /// </summary>
        public static string FeatureValues {
            get {
                return ResourceManager.GetString("FeatureValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вага опцій критерію, %.
        /// </summary>
        public static string FeatureValueTotal {
            get {
                return ResourceManager.GetString("FeatureValueTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вага опції, %.
        /// </summary>
        public static string FeatureValueValue {
            get {
                return ResourceManager.GetString("FeatureValueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; повинно бути датою..
        /// </summary>
        public static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; повинно бути числом..
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to перейдіть за цим посиланням.
        /// </summary>
        public static string FollowThisLink {
            get {
                return ResourceManager.GetString("FollowThisLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забули пароль?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вперед.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класифікатори ДК.
        /// </summary>
        public static string GsinCode {
            get {
                return ResourceManager.GetString("GsinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гарантія.
        /// </summary>
        public static string Guarantee {
            get {
                return ResourceManager.GetString("Guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ідентифікаційний код.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ідентифікатор.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр відповіді є недійсним або неправильний формат..
        /// </summary>
        public static string invalid_input_response {
            get {
                return ResourceManager.GetString("invalid_input_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секретний параметр відсутній..
        /// </summary>
        public static string invalid_input_secret {
            get {
                return ResourceManager.GetString("invalid_input_secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невдала спроба авторизації..
        /// </summary>
        public static string InvalidloginAttempt {
            get {
                return ResourceManager.GetString("InvalidloginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предмет закупівлі.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключове слово.
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мова.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uk.
        /// </summary>
        public static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA.
        /// </summary>
        public static string LanguageShortName {
            get {
                return ResourceManager.GetString("LanguageShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юридична особа.
        /// </summary>
        public static string LegalCompany {
            get {
                return ResourceManager.GetString("LegalCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наіменування орзанізації.
        /// </summary>
        public static string LegalName {
            get {
                return ResourceManager.GetString("LegalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наіменування орзанізації англ..
        /// </summary>
        public static string LegalNameEn {
            get {
                return ResourceManager.GetString("LegalNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місце.
        /// </summary>
        public static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Використовуйте локальну обліковий запис, щоб увійти.
        /// </summary>
        public static string LoginUnderLine {
            get {
                return ResourceManager.GetString("LoginUnderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довжина.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лот.
        /// </summary>
        public static string Lot {
            get {
                return ResourceManager.GetString("Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна вага всіх нецінових критеріїв однієї пропозиції не може перевищувати 30%..
        /// </summary>
        public static string MaximumNonPriceCriteriaMessage {
            get {
                return ResourceManager.GetString("MaximumNonPriceCriteriaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значення поля &quot;{0}&quot; не може бути більше {1}..
        /// </summary>
        public static string MaxLengthAttribute {
            get {
                return ResourceManager.GetString("MaxLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список заявок на участь в торгах.
        /// </summary>
        public static string MemberTenders {
            get {
                return ResourceManager.GetString("MemberTenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повідомлення.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По-батькові.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаг зниження ставки.
        /// </summary>
        public static string MinimalStep {
            get {
                return ResourceManager.GetString("MinimalStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значення поля &quot;{0}&quot; не може бути менше {1}..
        /// </summary>
        public static string MinLengthAttribute {
            get {
                return ResourceManager.GetString("MinLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр відповіді відсутній..
        /// </summary>
        public static string missing_input_response {
            get {
                return ResourceManager.GetString("missing_input_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секретний параметр недійсний або має неправильний формат..
        /// </summary>
        public static string missing_input_secret {
            get {
                return ResourceManager.GetString("missing_input_secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найбільш економічно вигідна пропозиція.
        /// </summary>
        public static string MostEconomicallyBetterOffer {
            get {
                return ResourceManager.GetString("MostEconomicallyBetterOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список заявок на замовлення торгів.
        /// </summary>
        public static string MyTenders {
            get {
                return ResourceManager.GetString("MyTenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наіменування.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наіменування англ..
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти в кабінет.
        /// </summary>
        public static string NavigateToCabinet {
            get {
                return ResourceManager.GetString("NavigateToCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти в закупівлі.
        /// </summary>
        public static string NavigateToItems {
            get {
                return ResourceManager.GetString("NavigateToItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти до тендеру.
        /// </summary>
        public static string NavigateToTender {
            get {
                return ResourceManager.GetString("NavigateToTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наступний.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ні.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Об&apos;єкт.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відсоток %.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Періоди.
        /// </summary>
        public static string Periods {
            get {
                return ResourceManager.GetString("Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персональний кабінет.
        /// </summary>
        public static string PersonalCabinet {
            get {
                return ResourceManager.GetString("PersonalCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персональні данні.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фізична особа.
        /// </summary>
        public static string PhysicalCompany {
            get {
                return ResourceManager.GetString("PhysicalCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер плану.
        /// </summary>
        public static string PlanNumber {
            get {
                return ResourceManager.GetString("PlanNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поштовий код.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планова дата початку процедури.
        /// </summary>
        public static string ProcedurePeriod {
            get {
                return ResourceManager.GetString("ProcedurePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип процедури.
        /// </summary>
        public static string ProcedureType {
            get {
                return ResourceManager.GetString("ProcedureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закупка.
        /// </summary>
        public static string Procurement {
            get {
                return ResourceManager.GetString("Procurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № закупівлі.
        /// </summary>
        public static string ProcurementNumber {
            get {
                return ResourceManager.GetString("ProcurementNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Об&apos;єкти закупівлі.
        /// </summary>
        public static string ProcurementObjects {
            get {
                return ResourceManager.GetString("ProcurementObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замовник.
        /// </summary>
        public static string Procurer {
            get {
                return ResourceManager.GetString("Procurer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування профілю.
        /// </summary>
        public static string ProfileSettings {
            get {
                return ResourceManager.GetString("ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значення &quot;{0}&quot; неправильне для {1}..
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значення обов&apos;язкове..
        /// </summary>
        public static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропозиції.
        /// </summary>
        public static string Proposition {
            get {
                return ResourceManager.GetString("Proposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постачальнику.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взяти участь у закупівлях.
        /// </summary>
        public static string ProviderUnderLine {
            get {
                return ResourceManager.GetString("ProviderUnderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опублікувати.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата кваліфікації.
        /// </summary>
        public static string QualificationDate {
            get {
                return ResourceManager.GetString("QualificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Питання.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підстава.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обгрунтування.
        /// </summary>
        public static string Reasoning {
            get {
                return ResourceManager.GetString("Reasoning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регіон.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація нового користувача.
        /// </summary>
        public static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація завершена.
        /// </summary>
        public static string RegistrationCompleted {
            get {
                return ResourceManager.GetString("RegistrationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалось завершити реєстрацію.
        /// </summary>
        public static string RegistrationError {
            get {
                return ResourceManager.GetString("RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Об&apos;єкт.
        /// </summary>
        public static string RelatedItem {
            get {
                return ResourceManager.GetString("RelatedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запам&apos;ятати мене.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; обов&apos;язкове..
        /// </summary>
        public static string RequiredAttribute {
            get {
                return ResourceManager.GetString("RequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відповідь.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип відповіді.
        /// </summary>
        public static string ResolutionType {
            get {
                return ResourceManager.GetString("ResolutionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схема.
        /// </summary>
        public static string Scheme {
            get {
                return ResourceManager.GetString("Scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знайти.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметри пошуку.
        /// </summary>
        public static string SearchParameters {
            get {
                return ResourceManager.GetString("SearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук закупівлі.
        /// </summary>
        public static string SearchTender {
            get {
                return ResourceManager.GetString("SearchTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук закупівлі.
        /// </summary>
        public static string SearchUnderLine {
            get {
                return ResourceManager.GetString("SearchUnderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть тип оголошення.
        /// </summary>
        public static string SelectTenderType {
            get {
                return ResourceManager.GetString("SelectTenderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Capital.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Початок періоду.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вулиця.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; не може бути більше {1} символів..
        /// </summary>
        public static string StringLengthAttribute {
            get {
                return ResourceManager.GetString("StringLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служба підтримки.
        /// </summary>
        public static string SupportService {
            get {
                return ResourceManager.GetString("SupportService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@e-capital.com.
        /// </summary>
        public static string SupportServiceEmail {
            get {
                return ResourceManager.GetString("SupportServiceEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +38(050) 1234-56-78.
        /// </summary>
        public static string SupportServicePhone {
            get {
                return ResourceManager.GetString("SupportServicePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тарифи.
        /// </summary>
        public static string Tariff {
            get {
                return ResourceManager.GetString("Tariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тендер.
        /// </summary>
        public static string Tender {
            get {
                return ResourceManager.GetString("Tender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переговорна процедура для потреб оборони.
        /// </summary>
        public static string TenderDefense {
            get {
                return ResourceManager.GetString("TenderDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталі тендеру.
        /// </summary>
        public static string TenderDetails {
            get {
                return ResourceManager.GetString("TenderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переговорна процедура.
        /// </summary>
        public static string TenderLimited {
            get {
                return ResourceManager.GetString("TenderLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переговорна процедура скорочена.
        /// </summary>
        public static string TenderLimitedQuick {
            get {
                return ResourceManager.GetString("TenderLimitedQuick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звіт про укладений договір.
        /// </summary>
        public static string TenderLimitedReporting {
            get {
                return ResourceManager.GetString("TenderLimitedReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок англ..
        /// </summary>
        public static string TitleEn {
            get {
                return ResourceManager.GetString("TitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок укр..
        /// </summary>
        public static string TitleUk {
            get {
                return ResourceManager.GetString("TitleUk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щоб підтвердити свою електронну пошту.
        /// </summary>
        public static string ToConfirmEmail {
            get {
                return ResourceManager.GetString("ToConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Торгівельний майданчик.
        /// </summary>
        public static string TradePlatform {
            get {
                return ResourceManager.GetString("TradePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спробуйте ще раз пізніше, або зверніться с службу підтримки.
        /// </summary>
        public static string TrayAgainLater {
            get {
                return ResourceManager.GetString("TrayAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Україна.
        /// </summary>
        public static string Ukraine {
            get {
                return ResourceManager.GetString("Ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одиниця виміру.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значення.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очікувана вартість закупівлі.
        /// </summary>
        public static string ValueAmount {
            get {
                return ResourceManager.GetString("ValueAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включаючи ПДВ.
        /// </summary>
        public static string VATIncluded {
            get {
                return ResourceManager.GetString("VATIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без ПДВ.
        /// </summary>
        public static string VATIncludeFalse {
            get {
                return ResourceManager.GetString("VATIncludeFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З ПДВ.
        /// </summary>
        public static string VATIncludeTrue {
            get {
                return ResourceManager.GetString("VATIncludeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З нами вже співпрацюють.
        /// </summary>
        public static string WorkWithUs {
            get {
                return ResourceManager.GetString("WorkWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Так.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви можете змінити будь-які дані на сторінці &quot;{0}&quot;..
        /// </summary>
        public static string YouCanChangeDataIn {
            get {
                return ResourceManager.GetString("YouCanChangeDataIn", resourceCulture);
            }
        }
    }
}
